version: '3.8'
services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - moodle_data:/var/www/html
      - moodle_data:/var/www/html/moodle
      - moodle_uploads:/var/www/html/moodledata/filedir
      - moodle_plugins:/var/www/html/moodledata/plugindata
    environment:
      MOODLE_DB_TYPE: mysqli
      MOODLE_DB_HOST: db
      MOODLE_DB_PORT: 3306
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodleuser
      MOODLE_DB_PASSWORD: moodlepassword
    depends_on:
      - db
    networks:
      - moodle_net

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    tmpfs:
      - /var/run/mysqld
    networks:
      - moodle_net
    

networks:
  moodle_net:

volumes:
  db_data:
  moodle_data:
  moodle_uploads:
  moodle_plugins: